/** Fonts available in the Fortune Sheet toolbar (index = cell.ff). */
export const EXCEL_FONT_ARRAY = [
    'Arial',
    'Arial Black',
    'Arial Narrow',
    'Calibri',
    'Calibri Light',
    'Cambria',
    'Candara',
    'Century Gothic',
    'Comic Sans MS',
    'Consolas',
    'Constantia',
    'Corbel',
    'Courier New',
    'Franklin Gothic Medium',
    'Garamond',
    'Georgia',
    'Helvetica',
    'Helvetica Neue',
    'Impact',
    'Lucida Console',
    'Lucida Sans Unicode',
    'Palatino Linotype',
    'Segoe UI',
    'Tahoma',
    'Times New Roman',
    'Trebuchet MS',
    'Verdana',
    'Book Antiqua',
    'Bookman Old Style',
    'Century Schoolbook',
    'Copperplate Gothic',
    'Didot',
    'Futura',
    'Gill Sans',
    'Hoefler Text',
    'Monaco',
    'Optima',
    'Perpetua',
    'Rockwell',
    'Baskerville',
    'Bodoni MT',
    'Brush Script MT',
    'Chalkboard',
    'Charcoal',
    'Geneva',
    'Gill Sans MT',
    'Herculanum',
    'Marker Felt',
    'Menlo',
    'Noteworthy',
    'Papyrus',
    'Phosphate',
    'Skia',
    'Snell Roundhand',
    'Zapfino',
    'Microsoft YaHei',
    'SimSun',
    'SimHei',
    'KaiTi',
    'FangSong',
    'NSimSun',
    'STXihei',
    'STXingkai',
    'STLiti',
    'PingFang SC',
    'Hiragino Sans',
    'Yu Gothic',
    'Meiryo',
    'Malgun Gothic',
    'Apple SD Gothic Neo',
    'Roboto',
    'Open Sans',
    'Lato',
    'Montserrat',
    'Source Sans Pro',
    'Ubuntu',
    'Fira Sans',
    'PT Sans',
    'Oswald',
    'Raleway',
    'Merriweather',
    'Playfair Display',
    'Libre Baskerville',
    'IBM Plex Sans',
    'Inter',
    'Work Sans',
    'Nunito',
    'Poppins',
    'DM Sans',
    'Manrope',
];

export function buildFontJson(fonts) {
    const json = {};
    fonts.forEach((name, index) => {
        json[String(name).toLowerCase()] = index;
    });
    return json;
}
