/** Palantir chart hues — muted violet / grey / white scale (no green/red/orange) */

export const PAL_CHART_SERIES = [
    '#6d5dfc',
    '#8577ff',
    '#a1a1aa',
    '#71717a',
    '#c4b5fd',
    '#52525b',
    '#d4d4d8',
    '#4c4c5c',
    '#e4e4e7',
    '#3f3f46',
];

export const PAL_NAV_TONES = {
    dashboard: { fg: 'var(--pal-brand)', bg: 'var(--pal-tag-bg)' },
    cars: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    checkout: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    parkedCheckout: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    operations: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    returns: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    damage: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    service: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    serviceFirms: { fg: 'var(--pal-muted)', bg: 'var(--pal-surface-high)' },
    office: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    officeReturns: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    frontDeskCustomers: { fg: 'var(--pal-brand)', bg: 'var(--pal-tag-bg)' },
    stripeCustomers: { fg: 'var(--pal-brand)', bg: 'var(--pal-tag-bg)' },
    files: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    excel: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    workingTimetable: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    protocols: { fg: 'var(--pal-muted)', bg: 'var(--pal-surface-high)' },
    shuttle: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    analytics: { fg: 'var(--pal-brand)', bg: 'var(--pal-tag-bg)' },
    reports: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    assistantNumbers: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminUserManagement: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    chOperationsPanel: { fg: 'var(--pal-brand)', bg: 'var(--pal-tag-bg)' },
    swissOps: { fg: 'var(--vs-violet, var(--erpx-brand))', bg: 'var(--pal-tag-bg)' },
    adminFranchises: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminSecurityOps: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminProcessOperations: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminFirebaseConnection: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminPhoneFormat: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminABTesting: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    adminActivityLog: { fg: 'var(--pal-muted)', bg: 'var(--pal-surface-high)' },
    adminFormatValidation: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
    signOut: { fg: 'var(--erpx-ink-muted)', bg: 'var(--erpx-subtle)' },
};
